### ISSUE TITLE
'Added by' not showing up

### ISSUE THREAD

**Issue by mikobeng** [GentlyTech/spicetify-extensions#1]
-- Versions --
Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.32.1
Theme: Bloom / darkmono
Extensions: group-session.js, CoverAmbience.js, imaged-folders.js, fullAppDisplay.js, beautiful-lyrics.js, playNextWrapper.js, QueueTime.js, who-added.js
Custom apps: marketplace, lyrics-plus, ncs-visualizer

-- Issue --
It only shows which playlist the song is being played from but not who added the song for me.

![image](https://github.com/GentlyTech/spicetify-extensions/assets/79459895/5ed28e2f-18d3-4c77-be10-aabf61bc76fd)

**Comment by mikobeng** [comment]
I've figured out the issue.

Spicetify might have changed the properties of playerState in and update somewhere, so what might have been originally been `track` is now `item`.

There are two instances of `e.track` in the script, search and replace them with `e.item`.

**Comment by GentlyTech** [comment]
Thanks for the tip - that seems to have been it.

Should be fixed now?

**Comment by mikobeng** [comment]
Yup, it did the trick.
